# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
      
      - name: Publish API
        run: dotnet publish -c Release --runtime win-x64 -o ./publish/SimplePlanePerformance.WebAPI ./src/SimplePlanePerformance.WebAPI
        
      - name: Restore NPM dependancies
        run: npm ci
        working-directory: src/SimplePlanePerformance.Client

      - name: Publish Client
        run: npm run build
        working-directory: src/SimplePlanePerformance.Client
        
      - name: Copy Client to publish
        run: cp -R ./src/SimplePlanePerformance.Client/dist/simple-plane-performance.client ./publish/SimplePlanePerformance.Client
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.2
        with:
          name: simpleplaneperformance-win-x64
          retention-days: 1
          path: ./publish/*
          if-no-files-found: error
      
    
  deploy:
    runs-on: planeperformance.emeni.local
    needs: [ build ]
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.6
        with:
          name: simpleplaneperformance-win-x64
          
      - name: Stop API app pool
        run: Stop-WebAppPool -Name "SimplePlanePerformance.WebAPI"
        continue-on-error: true

      - name: Stop Client app pool
        run: Stop-WebAppPool -Name "SimplePlanePerformance.Client"
        continue-on-error: true

      - name: Sleep for 5 seconds
        run: Start-Sleep -s 5
        shell: powershell
        
      - name: Delete old API files
        run: Remove-Item * -Exclude appsettings.Production.json -Recurse
        working-directory: E:\Apps\SimplePlanePerformance.WebAPI\

      - name: Delete old Client files
        run: Remove-Item * -Recurse
        working-directory: E:\Apps\SimplePlanePerformance.Client\
        
      - name: Copy API files
        run: cp -R .\SimplePlanePerformance.WebAPI\* E:\Apps\SimplePlanePerformance.WebAPI\
        working-directory: ${{ github.workspace }}
        
      - name: Copy Client files
        run: cp -R .\SimplePlanePerformance.Client\browser\* E:\Apps\SimplePlanePerformance.Client\
        working-directory: ${{ github.workspace }}
        
      - name: Start API app pool
        run: Start-WebAppPool -Name "SimplePlanePerformance.WebAPI"

      - name: Start Client app pool
        run: Start-WebAppPool -Name "SimplePlanePerformance.Client"